language: generic
os: osx
osx_image: xcode11.2
python: '3.7'
git:
  depth: false
#addons:
#  homebrew:
#    packages:
#    - python3
#    - acpica
branches:
  only:
  - master
env:
  global:
  - FORCE_INSTALL=1
  - secure: nKPBTwDx3sb0s3Rk/W/1qFY5ZmB/WBeLIKuL3FmLpCn+pQUmY4Xu6cqkEJYBF/iOVHgla50anRA+EzaGGfkga1LZVRry26MCDDFcjOCrWRT0T0NXooMX1Goo5sxT216X2uZUL8s6tkr6zohUIz/ICJoqgpdkaD/LYoMynLBWBKzFqe7hBuRZMX1Ulxo7PjA19YofqE9Kse53uIKLMzk8iGSnHcoqt/+gssrO0MEJLgAAB0pznfv5i1SenkpMmWzGmywgq3wf/VyCgncIQLVnmBYOaLhiA6GwZakN7KLtZVdjNnrDx7iUO4u0OuzndPXYK98DqzRPwgdsQIhLqaK5I3ojYJ5H71o1Z3C5sHR+B5XymStL7BOhLf5s4uZbbVVrTtXzfqjn2+ZXIfvvfxsb2HKlt65uojKLBOO9R3ddMRULgx0OFjHvar08B/21eGUJQtlNZ1Ow/vGHicDe8hV61zz2MODZ7qay4s+TGFo+wgbrVEDzErjHzKCzna8s29lhj3wWUHztxcXzUIFvvKxrCyT7pCdXcG2zjAf+b9efRvr7vIX5mCPKR9Zoy0B17g+fDTaO64WP7ZY+iW9X0Foga/okrLBATXBMQ23FJHg0Rd6eXEttVlkQJ5QJ5UYjCQFojATVnw9xIZ84VqP1NBTT63VV8Gaw145dMDKhaDPhWcU=
before_install:
- brew install 
- openssl aes-256-cbc -K $encrypted_20950518413d_key -iv $encrypted_20950518413d_iv
  -in gh\ token.txt.enc -out gh\ token.txt -d
- wget -P ~/ https://raw.githubusercontent.com/dhinakg/travis-ci-discord-webhook/master/send.sh
- chmod +x ~/send.sh
- "~/send.sh started $WEBHOOK_URL"
install:
- brew install python3
- brew install acpica
- python3 -m pip install -U pip
- pip3 install hammock python-dateutil datetime termcolor
- git fetch origin builds:builds
script:
- git worktree add Push builds
- cp Push/config.json .
- cp Push/last_updated.txt .
- python3 -u check_ratelimit.py
- python3 -u updater.py
- python3 -u check_ratelimit.py
- mv config.json Push
- mv last_updated.txt Push
- rsync -a Builds/ Push/
after_success:
- ls Push
- "~/send.sh success $WEBHOOK_URL"
after_failure:
- "~/send.sh failure $WEBHOOK_URL"
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: iWhzS68yDDp3tMZ65vpR6h/W6swA9SN5g6aMOfyPhOsd3Be0XpPuPlJ5kiOmRAtQ92sOYIs+zOSqrgjN4B8LXHAaTAvSVgPFx4K5q+jKY//QC0pNYw0gA0Qbtg6Gn0uVISalBcGy7UGpFsp4DMO9/TzrE1UJqpAKzsmsAM6rPq8ledrHO6cHn2ggTbfWgKlxeuhzZkmzw1sE2wO/Jv1WedmR4ei4uD/fsocP+oInp6a3iIBrHitdOTT7kUZYmOUqReazU2dtItXcjuwh2qET7U//YDIdooizlL3Vhm+NU4wUZ91/h2LlEG/uSJUj2kHo1yArgt1NRVO28BcjYHUU1l+PoDk1RtAp9JDWJR3dg6AeVmKO812sel4kwrBOxA1+Jzvb6brCS50D3BjXJmjQtlEwCPQuuq5BV3UPrWrF2Bhpmd7anhRqPBFdKbd4Eg5aSLHu5U8vhzd34OWOHiFlvUnHmpsKJyKe8hD59vZ4ah5HcXoYNz1ZO5N7pzcTxPEfFd1Q+C5rvgoXe4YWW/ma2VCMSWHWMtpKzITnn6DgQpmAYbKX/tyF3FI5HeDqM3eXeHjfA/OnL9r+8VmIulrLVo2uSX2q7n2dSZ7XslJLq7MkIwBHtrO3zJWpmenpCGolxPeM03AYNdgyj3mH81K694K4BRumI1RxLtfCpqOefpU=
  keep_history: true
  target_branch: builds
  local_dir: Push
  on:
    branch: master
