title: "Test"
description: >- # this means to ignore newlines until "baseurl:"
  Test
baseurl: "ktextrepo-beta" # the subpath of your site, e.g. /blog
url: "https://dhinakg.github.io/ktextrepo-beta" # the base hostname & protocol for your site, e.g. http://example.com
github_username: dhinakg
theme: minima