name: Build
on:
  push:
    branches:
      - github-actions
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  FORCE_INSTALL: 1
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/setup-ruby@v1
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: true
          ref: github-actions
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python3 -m pip install -U pip
          pip3 install hammock python-dateutil datetime termcolor purl python-magic
      - name: Copy Token
        run: echo ${{ secrets.GITHUB_TOKEN }} > gh\ token.txt
      - name: Check Parallel
        run: python3 -u parallel_check.py
      - name: Install Build Dependencies
        run: |
          HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install acpica libmagic
      - name: Set Up Working Tree
        run: |
          git clone https://github.com/dhinakg/ktextrepo-beta.git Push --depth 1 --single-branch --branch builds --sparse --filter=blob:none
          cp Push/config.json .
          cp Push/last_updated.txt .
      - name: Check Ratelimit
        run: python3 -u check_ratelimit.py
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v2
      - name: Send Starting Notification
        if: always()
        env:
          JOB_STATUS: started
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          git clone https://github.com/dhinakg/github-actions-discord-webhook.git webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
      - name: Run Builder
        run: python3 -u updater.py
      - name: Check Ratelimit
        run: python3 -u check_ratelimit.py
      - name: Sync Builds
        run: |
          mv config.json Push
          mv last_updated.txt Push
          ls Push
          cd Push
      - uses: fregante/setup-git-token@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: Push
      - name: Push Builds
        run: |
          cd Push
          git config --global user.name "Dhinak G"
          git config --global user.email "dhinakg@users.noreply.github.com"
          git add config.json last_updated.txt
          git commit -m "Deploying to builds"
          git push
      - name: Send Notification
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
          JOB_ID: ${{ github.job }}
        run: |
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
