name: Build
on:
  push:
    branches:
      - github-actions
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  FORCE_INSTALL: 1
  HAS_OPENSSL_BUILD: 1
  HAS_OPENSSL_W32BUILD: 0
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-ruby@v1
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          ref: github-actions
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python Dependencies
        run: |
          python3 -m pip install -U pip
          pip3 install hammock python-dateutil datetime termcolor2 purl python-magic humanize gitpython cryptography
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        with:
          limit-access-to-actor: true
      - name: Install Build Dependencies
        run: |
          HOMEBREW_NO_INSTALL_CLEANUP=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install acpica libmagic mingw-w64 openssl
      - uses: fregante/setup-git-user@3a4c7216882eacd989bf2bc80fabbf9bca971967
      - name: Set Up Working Tree
        uses: actions/checkout@v2
        with:
          persist-credentials: true
          ref: builds
          path: Config
      - name: Check Ratelimit
        run: python3 -u check_ratelimit.py ${{ secrets.GITHUB_TOKEN }}
      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v2
      - name: Run Builder
        run: python3 -u updater.py ${{ secrets.GITHUB_TOKEN }} ${{ secrets.WEBHOOK_URL }} ${{ secrets.PAYLOAD_KEY }}
        env:
          JOB_NAME: ${{ github.job }}
      - name: Check Ratelimit
        run: python3 -u check_ratelimit.py ${{ secrets.GITHUB_TOKEN }}
      # No longer needed
      # - name: Sort Config
      #   run: python3 -u update_config.py
